### PR TITLE
test: Mock only service call in AHS device initialization

### PR DESCRIPTION
**Pull request by yitchen-tim**
*Description of changes:*
Add noise model to mock aws device in unit test. This is an update for introducing BDK PR https://github.com/amazon-braket/amazon-braket-sdk-python/pull/850

*Testing done:*
tox

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/main/README.md) and [API docs](https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by speller26** [comment]
Why not include this in #850? The change doesn't make sense on its own.

**Comment by yitchen-tim** [comment]
I didn't see a way for a PR to make changes in two different repository? Is there a better way than having two separate PRs?

**Comment by speller26** [comment]
Oops, thought this one was also in the SDK; in that case we'll just hold off until that PR is finalized. In the meantime, the prefix of the PR should be test: rather than fix:

**Comment by speller26** [comment]
The fact that we need to add the field here _before_ we merge the SDK change indicates a problem with how our mocks are set up; we shouldn't have to add in a yet-to-be-introduced property here

**Comment by yitchen-tim** [comment]
yes, it's related to [this mock](https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/8c6fd32b5b4d8719967bbdf5f6560d08dc89c045/test/unit_tests/test_ahs_device.py#L233). It should mock the individual attributes, instead of filling in what's necessary to a Mock.

**Comment by speller26** [comment]
Instead of adding a `_noise_model` attribute to the mock device for the test case, try replacing
https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/8c6fd32b5b4d8719967bbdf5f6560d08dc89c045/test/unit_tests/test_ahs_device.py#L236-L237
with
```python
m.setattr(AwsDevice, "_get_session_and_initialize", lambda self, *args, **kwargs: MockAwsSession) 
```
Instead of mocking out the entirety of `__init__`, and all the useful attributes that come with it, this will only mock out the [service call](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/src/braket/aws/aws_device.py#L104), which should be much more robust.

**Comment by yitchen-tim** [comment]
Great, this solution is working! I also tested locally that https://github.com/amazon-braket/amazon-braket-sdk-python/pull/850 will pass with this fix.

**Review by speller26 — APPROVED** [review]

**Pull request merged**
