### PR TITLE
fix: Translate `Sum` for adjoint gradient

### PR DESCRIPTION
**Pull request by speller26**
*Issue #, if available:*

*Description of changes:*

The plugin only translates `Hamiltonian`s for the adjoint gradient, but Hamiltonians are often actually `Sum` objects. This change adds `Sum` observable translation.

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/main/README.md) and [API docs](https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by speller26** [comment]
Coverage loss probably caused by migration to PennyLane 0.36

**Comment by astralcai** [comment]
> Coverage loss probably caused by migration to PennyLane 0.36

Yes, for context, in v0.36, `qml.Hamiltonian` dispatches to `LinearCombination`, which extends `CompositeOp`, which means that the next branch is never reached unless a legacy `Hamiltonian` is explicitly created using `qml.ops.Hamiltonian`.

**Review by math411 — DISMISSED** [review]

**Review by math411 — APPROVED** [review]

**Comment by math411** [comment]
Confirming that @speller26's changes look good. Deferring to @speller26 to review the changes I have added.

**Comment by speller26** [comment]
Tests LGTM!

**Pull request merged**
